version: "2.0"
services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile
    command: start-notebook.sh --NotebookApp.token=''
    environment:
      - JUPYTER_ENABLE_LAB=true
    ports:
      - 8888:8888
      - 8050:8050
    volumes:
      - ./notebooks:/home/jovyan/work
